// <auto-generated />
using System;
using Mealie.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mealie.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260426011323_AddReportQueueFields")]
    partial class AddReportQueueFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("CategoryCookbook", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CookbookId")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriesId", "CookbookId");

                    b.HasIndex("CookbookId");

                    b.ToTable("cookbooks_to_categories", (string)null);
                });

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipesId")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriesId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("recipes_to_categories", (string)null);
                });

            modelBuilder.Entity("CookbookTag", b =>
                {
                    b.Property<Guid>("CookbookId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("CookbookId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("cookbooks_to_tags", (string)null);
                });

            modelBuilder.Entity("CookbookTool", b =>
                {
                    b.Property<Guid>("CookbookId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToolsId")
                        .HasColumnType("TEXT");

                    b.HasKey("CookbookId", "ToolsId");

                    b.HasIndex("ToolsId");

                    b.ToTable("cookbooks_to_tools", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("long_live_tokens", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueuedFilePath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("QueuedHouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("QueuedUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.ReportEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportEntries");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Admin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Advanced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanInvite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManageHousehold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanOrganize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastReadAnnouncement")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowAnnouncements")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FullName");

                    b.HasIndex("GroupId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Ingredients.IngredientFood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnHand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PluralName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UnitId");

                    b.ToTable("ingredient_foods", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Ingredients.IngredientFoodAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("ingredient_foods_aliases", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Ingredients.IngredientUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Fraction")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluralAbbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("PluralName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAbbreviation")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("ingredient_units", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Organizers.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Organizers.Cookbook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Public")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireAllCategories")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("cookbooks", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Organizers.GroupInviteToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("invite_tokens", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Organizers.MultiPurposeLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("multi_purpose_labels", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Organizers.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Organizers.Tool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnHand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("tools", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Planning.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("GroupId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("group_meal_plans", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Planning.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("shopping_lists", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Planning.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Checked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisableAmount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FoodId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFood")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LabelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("LabelId");

                    b.HasIndex("ShoppingListId");

                    b.HasIndex("UnitId");

                    b.ToTable("shopping_list_items", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Planning.ShoppingListItemRecipeReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RecipeQuantity")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecipeQuantityId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RecipeScale")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShoppingListItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("ShoppingListItemId");

                    b.ToTable("shopping_list_item_recipe_reference", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Planning.ShoppingListRecipeReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RecipeScale")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("shopping_list_recipe_reference", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CookTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisableAmount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOcr")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastMade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrepTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeYield")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("Slug", "GroupId")
                        .IsUnique();

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.RecipeAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_assets", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.RecipeComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("recipe_comments", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisableAmount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FoodId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFood")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalText")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitId");

                    b.ToTable("recipes_ingredients", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.RecipeInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientReferencesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("ingredient_references");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_instructions", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.RecipeNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.RecipeShareToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_share_tokens", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.RecipeTimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_timeline_events", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Settings.EventNotifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprisUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("group_events_notifiers", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Settings.GroupPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstDayOfWeek")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PrivateGroup")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("group_preferences", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Settings.HouseholdPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstDayOfWeek")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PrivateHousehold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeDisableAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeDisableComments")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeLandscapeView")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipePublic")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeShowAssets")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeShowNutrition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId")
                        .IsUnique();

                    b.ToTable("household_preferences", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Settings.ServerTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Log")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("server_tasks", (string)null);
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Settings.Webhook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("webhook_urls", (string)null);
                });

            modelBuilder.Entity("RecipeTag", b =>
                {
                    b.Property<Guid>("RecipesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("RecipesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("recipes_to_tags", (string)null);
                });

            modelBuilder.Entity("RecipeTool", b =>
                {
                    b.Property<Guid>("RecipesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToolsId")
                        .HasColumnType("TEXT");

                    b.HasKey("RecipesId", "ToolsId");

                    b.HasIndex("ToolsId");

                    b.ToTable("recipes_to_tools", (string)null);
                });

            modelBuilder.Entity("RecipeUser", b =>
                {
                    b.Property<Guid>("FavoriteRecipesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("FavoriteRecipesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("users_to_recipes", (string)null);
                });

            modelBuilder.Entity("CategoryCookbook", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Organizers.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Organizers.Cookbook", null)
                        .WithMany()
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Organizers.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CookbookTag", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Organizers.Cookbook", null)
                        .WithMany()
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Organizers.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CookbookTool", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Organizers.Cookbook", null)
                        .WithMany()
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Organizers.Tool", null)
                        .WithMany()
                        .HasForeignKey("ToolsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.ApiKey", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.Household", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany("Households")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.Report", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.ReportEntry", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Report", "Report")
                        .WithMany("Entries")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.User", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Core.Household", "Household")
                        .WithMany("Users")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Ingredients.IngredientFood", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany("Foods")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Ingredients.IngredientUnit", "Unit")
                        .WithMany("Foods")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Ingredients.IngredientFoodAlias", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Ingredients.IngredientFood", "Food")
                        .WithMany("Aliases")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Ingredients.IngredientUnit", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany("Units")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Organizers.Category", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany("Categories")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Organizers.Cookbook", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany("Cookbooks")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Core.Household", "Household")
                        .WithMany("Cookbooks")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Organizers.GroupInviteToken", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany("InviteTokens")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Organizers.MultiPurposeLabel", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany("Labels")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Organizers.Tag", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany("Tags")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Organizers.Tool", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany("Tools")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Planning.MealPlan", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany("MealPlans")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Core.Household", "Household")
                        .WithMany("MealPlans")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mealie.Domain.Entities.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Household");

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Planning.ShoppingList", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Core.Household", "Household")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Planning.ShoppingListItem", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Ingredients.IngredientFood", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mealie.Domain.Entities.Organizers.MultiPurposeLabel", "Label")
                        .WithMany("ShoppingItems")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mealie.Domain.Entities.Planning.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Ingredients.IngredientUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Food");

                    b.Navigation("Label");

                    b.Navigation("ShoppingList");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Planning.ShoppingListItemRecipeReference", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Planning.ShoppingListItem", "ShoppingListItem")
                        .WithMany("RecipeReferences")
                        .HasForeignKey("ShoppingListItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("ShoppingListItem");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Planning.ShoppingListRecipeReference", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Planning.ShoppingList", "ShoppingList")
                        .WithMany("RecipeReferences")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.Recipe", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany("Recipes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Core.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Mealie.Domain.Entities.Recipes.Nutrition", "Nutrition", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Calories")
                                .HasColumnType("TEXT")
                                .HasColumnName("nutrition_calories");

                            b1.Property<string>("CarbohydrateContent")
                                .HasColumnType("TEXT")
                                .HasColumnName("nutrition_carbohydrate_content");

                            b1.Property<string>("FatContent")
                                .HasColumnType("TEXT")
                                .HasColumnName("nutrition_fat_content");

                            b1.Property<string>("FiberContent")
                                .HasColumnType("TEXT")
                                .HasColumnName("nutrition_fiber_content");

                            b1.Property<string>("ProteinContent")
                                .HasColumnType("TEXT")
                                .HasColumnName("nutrition_protein_content");

                            b1.Property<string>("SodiumContent")
                                .HasColumnType("TEXT")
                                .HasColumnName("nutrition_sodium_content");

                            b1.Property<string>("SugarContent")
                                .HasColumnType("TEXT")
                                .HasColumnName("nutrition_sugar_content");

                            b1.HasKey("RecipeId");

                            b1.ToTable("recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsOne("Mealie.Domain.Entities.Recipes.RecipeSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("DisableAmount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("settings_disable_amount");

                            b1.Property<bool>("DisableComments")
                                .HasColumnType("INTEGER")
                                .HasColumnName("settings_disable_comments");

                            b1.Property<bool>("LandscapeView")
                                .HasColumnType("INTEGER")
                                .HasColumnName("settings_landscape_view");

                            b1.Property<bool>("Locked")
                                .HasColumnType("INTEGER")
                                .HasColumnName("settings_locked");

                            b1.Property<bool>("Public")
                                .HasColumnType("INTEGER")
                                .HasColumnName("settings_public");

                            b1.Property<bool>("ShowAssets")
                                .HasColumnType("INTEGER")
                                .HasColumnName("settings_show_assets");

                            b1.Property<bool>("ShowNutrition")
                                .HasColumnType("INTEGER")
                                .HasColumnName("settings_show_nutrition");

                            b1.HasKey("RecipeId");

                            b1.ToTable("recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("Group");

                    b.Navigation("Household");

                    b.Navigation("Nutrition");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.RecipeAsset", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Assets")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.RecipeComment", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Core.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Ingredients.IngredientFood", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mealie.Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Ingredients.IngredientUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Food");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.RecipeInstruction", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeInstructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.RecipeNote", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Notes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.RecipeShareToken", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("ShareTokens")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.RecipeTimelineEvent", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("TimelineEvents")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Settings.EventNotifier", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Core.Household", "Household")
                        .WithMany("EventNotifiers")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Mealie.Domain.Entities.Settings.EventNotifierOptions", "Options", b1 =>
                        {
                            b1.Property<Guid>("EventNotifierId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("MealplanEntryCreated")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("RecipeCreated")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("RecipeDeleted")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("RecipeUpdated")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("ShoppingListCreated")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("ShoppingListDeleted")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("ShoppingListUpdated")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("TestMessage")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("UserSignup")
                                .HasColumnType("INTEGER");

                            b1.HasKey("EventNotifierId");

                            b1.ToTable("group_events_notifier_options", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EventNotifierId");
                        });

                    b.Navigation("Group");

                    b.Navigation("Household");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Settings.GroupPreferences", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithOne("Preferences")
                        .HasForeignKey("Mealie.Domain.Entities.Settings.GroupPreferences", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Settings.HouseholdPreferences", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Household", "Household")
                        .WithOne("Preferences")
                        .HasForeignKey("Mealie.Domain.Entities.Settings.HouseholdPreferences", "HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Settings.Webhook", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Core.Group", "Group")
                        .WithMany("Webhooks")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Core.Household", "Household")
                        .WithMany("Webhooks")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("RecipeTag", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Organizers.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeTool", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Organizers.Tool", null)
                        .WithMany()
                        .HasForeignKey("ToolsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeUser", b =>
                {
                    b.HasOne("Mealie.Domain.Entities.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("FavoriteRecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mealie.Domain.Entities.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.Group", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Cookbooks");

                    b.Navigation("Foods");

                    b.Navigation("Households");

                    b.Navigation("InviteTokens");

                    b.Navigation("Labels");

                    b.Navigation("MealPlans");

                    b.Navigation("Preferences");

                    b.Navigation("Recipes");

                    b.Navigation("ShoppingLists");

                    b.Navigation("Tags");

                    b.Navigation("Tools");

                    b.Navigation("Units");

                    b.Navigation("Users");

                    b.Navigation("Webhooks");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.Household", b =>
                {
                    b.Navigation("Cookbooks");

                    b.Navigation("EventNotifiers");

                    b.Navigation("MealPlans");

                    b.Navigation("Preferences");

                    b.Navigation("ShoppingLists");

                    b.Navigation("Users");

                    b.Navigation("Webhooks");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.Report", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Core.User", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Ingredients.IngredientFood", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Ingredients.IngredientUnit", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Organizers.MultiPurposeLabel", b =>
                {
                    b.Navigation("ShoppingItems");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Planning.ShoppingList", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("RecipeReferences");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Planning.ShoppingListItem", b =>
                {
                    b.Navigation("RecipeReferences");
                });

            modelBuilder.Entity("Mealie.Domain.Entities.Recipes.Recipe", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Comments");

                    b.Navigation("Notes");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipeInstructions");

                    b.Navigation("ShareTokens");

                    b.Navigation("TimelineEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
