<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Mealie.Domain\Mealie.Domain.csproj" />
    <ProjectReference Include="..\Mealie.Infrastructure\Mealie.Infrastructure.csproj" />
    <ProjectReference Include="..\Mealie.Shared\Mealie.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Lucene.Net" />
    <PackageReference Include="Lucene.Net.Analysis.Common" />
    <PackageReference Include="Lucene.Net.QueryParser" />
    <PackageReference Include="Riok.Mapperly" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
  </ItemGroup>

</Project>
