
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const EndPageContent: typeof import("../app/components/Domain/Admin/Setup/EndPageContent.vue")['default']
export const AnnouncementDialog: typeof import("../app/components/Domain/Announcement/AnnouncementDialog.vue")['default']
export const 202603271Welcome: typeof import("../app/components/Domain/Announcement/Announcements/2026-03-27_1_welcome.vue")['default']
export const CookbookEditor: typeof import("../app/components/Domain/Cookbook/CookbookEditor.vue")['default']
export const CookbookPage: typeof import("../app/components/Domain/Cookbook/CookbookPage.vue")['default']
export const GroupDataPage: typeof import("../app/components/Domain/Group/GroupDataPage.vue")['default']
export const GroupExportData: typeof import("../app/components/Domain/Group/GroupExportData.vue")['default']
export const GroupPreferencesEditor: typeof import("../app/components/Domain/Group/GroupPreferencesEditor.vue")['default']
export const GroupMealPlanDayContextMenu: typeof import("../app/components/Domain/Household/GroupMealPlanDayContextMenu.vue")['default']
export const GroupMealPlanRuleForm: typeof import("../app/components/Domain/Household/GroupMealPlanRuleForm.vue")['default']
export const GroupWebhookEditor: typeof import("../app/components/Domain/Household/GroupWebhookEditor.vue")['default']
export const HouseholdPreferencesEditor: typeof import("../app/components/Domain/Household/HouseholdPreferencesEditor.vue")['default']
export const QueryFilterBuilder: typeof import("../app/components/Domain/QueryFilterBuilder.vue")['default']
export const RecipeActionMenu: typeof import("../app/components/Domain/Recipe/RecipeActionMenu.vue")['default']
export const RecipeAssets: typeof import("../app/components/Domain/Recipe/RecipeAssets.vue")['default']
export const RecipeCard: typeof import("../app/components/Domain/Recipe/RecipeCard.vue")['default']
export const RecipeCardImage: typeof import("../app/components/Domain/Recipe/RecipeCardImage.vue")['default']
export const RecipeCardMobile: typeof import("../app/components/Domain/Recipe/RecipeCardMobile.vue")['default']
export const RecipeCardRating: typeof import("../app/components/Domain/Recipe/RecipeCardRating.vue")['default']
export const RecipeCardSection: typeof import("../app/components/Domain/Recipe/RecipeCardSection.vue")['default']
export const RecipeChips: typeof import("../app/components/Domain/Recipe/RecipeChips.vue")['default']
export const RecipeContextMenu: typeof import("../app/components/Domain/Recipe/RecipeContextMenu/RecipeContextMenu.vue")['default']
export const RecipeContextMenuContent: typeof import("../app/components/Domain/Recipe/RecipeContextMenu/RecipeContextMenuContent.vue")['default']
export const RecipeDataAliasManagerDialog: typeof import("../app/components/Domain/Recipe/RecipeDataAliasManagerDialog.vue")['default']
export const RecipeDataTable: typeof import("../app/components/Domain/Recipe/RecipeDataTable.vue")['default']
export const RecipeDialogAddToShoppingList: typeof import("../app/components/Domain/Recipe/RecipeDialogAddToShoppingList.vue")['default']
export const RecipeDialogBulkAdd: typeof import("../app/components/Domain/Recipe/RecipeDialogBulkAdd.vue")['default']
export const RecipeDialogPrintPreferences: typeof import("../app/components/Domain/Recipe/RecipeDialogPrintPreferences.vue")['default']
export const RecipeDialogSearch: typeof import("../app/components/Domain/Recipe/RecipeDialogSearch.vue")['default']
export const RecipeDialogShare: typeof import("../app/components/Domain/Recipe/RecipeDialogShare.vue")['default']
export const RecipeExplorerPage: typeof import("../app/components/Domain/Recipe/RecipeExplorerPage/RecipeExplorerPage.vue")['default']
export const RecipeExplorerPageSearch: typeof import("../app/components/Domain/Recipe/RecipeExplorerPage/RecipeExplorerPageParts/RecipeExplorerPageSearch.vue")['default']
export const RecipeExplorerPageSearchFilters: typeof import("../app/components/Domain/Recipe/RecipeExplorerPage/RecipeExplorerPageParts/RecipeExplorerPageSearchFilters.vue")['default']
export const RecipeFavoriteBadge: typeof import("../app/components/Domain/Recipe/RecipeFavoriteBadge.vue")['default']
export const RecipeImageUploadBtn: typeof import("../app/components/Domain/Recipe/RecipeImageUploadBtn.vue")['default']
export const RecipeIngredientEditor: typeof import("../app/components/Domain/Recipe/RecipeIngredientEditor.vue")['default']
export const RecipeIngredientHtml: typeof import("../app/components/Domain/Recipe/RecipeIngredientHtml.vue")['default']
export const RecipeIngredientListItem: typeof import("../app/components/Domain/Recipe/RecipeIngredientListItem.vue")['default']
export const RecipeIngredients: typeof import("../app/components/Domain/Recipe/RecipeIngredients.vue")['default']
export const RecipeLastMade: typeof import("../app/components/Domain/Recipe/RecipeLastMade.vue")['default']
export const RecipeList: typeof import("../app/components/Domain/Recipe/RecipeList.vue")['default']
export const RecipeNotes: typeof import("../app/components/Domain/Recipe/RecipeNotes.vue")['default']
export const RecipeNutrition: typeof import("../app/components/Domain/Recipe/RecipeNutrition.vue")['default']
export const RecipeOrganizerDialog: typeof import("../app/components/Domain/Recipe/RecipeOrganizerDialog.vue")['default']
export const RecipeOrganizerPage: typeof import("../app/components/Domain/Recipe/RecipeOrganizerPage.vue")['default']
export const RecipeOrganizerSelector: typeof import("../app/components/Domain/Recipe/RecipeOrganizerSelector.vue")['default']
export const RecipePage: typeof import("../app/components/Domain/Recipe/RecipePage/RecipePage.vue")['default']
export const RecipePageComments: typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageComments.vue")['default']
export const RecipePageEditorToolbar: typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageEditorToolbar.vue")['default']
export const RecipePageFooter: typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageFooter.vue")['default']
export const RecipePageHeader: typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageHeader.vue")['default']
export const RecipePageInfoCard: typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoCard.vue")['default']
export const RecipePageInfoCardImage: typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoCardImage.vue")['default']
export const RecipePageInfoEditor: typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoEditor.vue")['default']
export const RecipePageIngredientEditor: typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientEditor.vue")['default']
export const RecipePageIngredientToolsView: typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientToolsView.vue")['default']
export const RecipePageInstructions: typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInstructions.vue")['default']
export const RecipePageOrganizers: typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageOrganizers.vue")['default']
export const RecipePageParseDialog: typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageParseDialog.vue")['default']
export const RecipePageScale: typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageScale.vue")['default']
export const RecipePrintContainer: typeof import("../app/components/Domain/Recipe/RecipePrintContainer.vue")['default']
export const RecipePrintView: typeof import("../app/components/Domain/Recipe/RecipePrintView.vue")['default']
export const RecipeRating: typeof import("../app/components/Domain/Recipe/RecipeRating.vue")['default']
export const RecipeScaleEditButton: typeof import("../app/components/Domain/Recipe/RecipeScaleEditButton.vue")['default']
export const RecipeSettingsMenu: typeof import("../app/components/Domain/Recipe/RecipeSettingsMenu.vue")['default']
export const RecipeSettingsSwitches: typeof import("../app/components/Domain/Recipe/RecipeSettingsSwitches.vue")['default']
export const RecipeSuggestion: typeof import("../app/components/Domain/Recipe/RecipeSuggestion.vue")['default']
export const RecipeTimeCard: typeof import("../app/components/Domain/Recipe/RecipeTimeCard.vue")['default']
export const RecipeTimeline: typeof import("../app/components/Domain/Recipe/RecipeTimeline.vue")['default']
export const RecipeTimelineBadge: typeof import("../app/components/Domain/Recipe/RecipeTimelineBadge.vue")['default']
export const RecipeTimelineContextMenu: typeof import("../app/components/Domain/Recipe/RecipeTimelineContextMenu.vue")['default']
export const RecipeTimelineItem: typeof import("../app/components/Domain/Recipe/RecipeTimelineItem.vue")['default']
export const RecipeYield: typeof import("../app/components/Domain/Recipe/RecipeYield.vue")['default']
export const SearchFilter: typeof import("../app/components/Domain/SearchFilter.vue")['default']
export const MultiPurposeLabel: typeof import("../app/components/Domain/ShoppingList/MultiPurposeLabel.vue")['default']
export const MultiPurposeLabelSection: typeof import("../app/components/Domain/ShoppingList/MultiPurposeLabelSection.vue")['default']
export const ShoppingListItem: typeof import("../app/components/Domain/ShoppingList/ShoppingListItem.vue")['default']
export const ShoppingListItemEditor: typeof import("../app/components/Domain/ShoppingList/ShoppingListItemEditor.vue")['default']
export const UserAvatar: typeof import("../app/components/Domain/User/UserAvatar.vue")['default']
export const UserInviteDialog: typeof import("../app/components/Domain/User/UserInviteDialog.vue")['default']
export const UserPasswordStrength: typeof import("../app/components/Domain/User/UserPasswordStrength.vue")['default']
export const UserProfileLinkCard: typeof import("../app/components/Domain/User/UserProfileLinkCard.vue")['default']
export const UserRegistrationForm: typeof import("../app/components/Domain/User/UserRegistrationForm.vue")['default']
export const DefaultLayout: typeof import("../app/components/Layout/DefaultLayout.vue")['default']
export const AppFooter: typeof import("../app/components/Layout/LayoutParts/AppFooter.vue")['default']
export const AppHeader: typeof import("../app/components/Layout/LayoutParts/AppHeader.vue")['default']
export const AppScrollToTop: typeof import("../app/components/Layout/LayoutParts/AppScrollToTop.vue")['default']
export const AppSidebar: typeof import("../app/components/Layout/LayoutParts/AppSidebar.vue")['default']
export const TheSnackbar: typeof import("../app/components/Layout/LayoutParts/TheSnackbar.vue")['default']
export const AdvancedOnly: typeof import("../app/components/global/AdvancedOnly.vue")['default']
export const AppButtonCopy: typeof import("../app/components/global/AppButtonCopy.vue")['default']
export const AppButtonUpload: typeof import("../app/components/global/AppButtonUpload.vue")['default']
export const AppLoader: typeof import("../app/components/global/AppLoader.vue")['default']
export const AppLogo: typeof import("../app/components/global/AppLogo.vue")['default']
export const AppToolbar: typeof import("../app/components/global/AppToolbar.vue")['default']
export const AutoForm: typeof import("../app/components/global/AutoForm.vue")['default']
export const BannerExperimental: typeof import("../app/components/global/BannerExperimental.vue")['default']
export const BannerWarning: typeof import("../app/components/global/BannerWarning.vue")['default']
export const BaseButton: typeof import("../app/components/global/BaseButton.vue")['default']
export const BaseButtonGroup: typeof import("../app/components/global/BaseButtonGroup.vue")['default']
export const BaseCardSectionTitle: typeof import("../app/components/global/BaseCardSectionTitle.vue")['default']
export const BaseDialog: typeof import("../app/components/global/BaseDialog.vue")['default']
export const BaseDivider: typeof import("../app/components/global/BaseDivider.vue")['default']
export const BaseExpansionPanels: typeof import("../app/components/global/BaseExpansionPanels.vue")['default']
export const BaseOverflowButton: typeof import("../app/components/global/BaseOverflowButton.vue")['default']
export const BasePageTitle: typeof import("../app/components/global/BasePageTitle.vue")['default']
export const ButtonLink: typeof import("../app/components/global/ButtonLink.vue")['default']
export const ContextMenu: typeof import("../app/components/global/ContextMenu.vue")['default']
export const CrudTable: typeof import("../app/components/global/CrudTable.vue")['default']
export const DevDumpJson: typeof import("../app/components/global/DevDumpJson.vue")['default']
export const DocLink: typeof import("../app/components/global/DocLink.vue")['default']
export const DropZone: typeof import("../app/components/global/DropZone.vue")['default']
export const HelpIcon: typeof import("../app/components/global/HelpIcon.vue")['default']
export const ImageCropper: typeof import("../app/components/global/ImageCropper.vue")['default']
export const InputColor: typeof import("../app/components/global/InputColor.vue")['default']
export const InputLabelType: typeof import("../app/components/global/InputLabelType.vue")['default']
export const LanguageDialog: typeof import("../app/components/global/LanguageDialog.vue")['default']
export const MarkdownEditor: typeof import("../app/components/global/MarkdownEditor.vue")['default']
export const RecipeJsonEditor: typeof import("../app/components/global/RecipeJsonEditor.vue")['default']
export const ReportTable: typeof import("../app/components/global/ReportTable.vue")['default']
export const SafeMarkdown: typeof import("../app/components/global/SafeMarkdown.vue")['default']
export const StatsCards: typeof import("../app/components/global/StatsCards.vue")['default']
export const ToggleState: typeof import("../app/components/global/ToggleState.vue")['default']
export const WakelockSwitch: typeof import("../app/components/global/WakelockSwitch.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const VitePwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaAssets: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const PwaAppleImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const PwaAppleSplashScreenImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const PwaFaviconImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const PwaMaskableImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const PwaTransparentImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyEndPageContent: LazyComponent<typeof import("../app/components/Domain/Admin/Setup/EndPageContent.vue")['default']>
export const LazyAnnouncementDialog: LazyComponent<typeof import("../app/components/Domain/Announcement/AnnouncementDialog.vue")['default']>
export const Lazy202603271Welcome: LazyComponent<typeof import("../app/components/Domain/Announcement/Announcements/2026-03-27_1_welcome.vue")['default']>
export const LazyCookbookEditor: LazyComponent<typeof import("../app/components/Domain/Cookbook/CookbookEditor.vue")['default']>
export const LazyCookbookPage: LazyComponent<typeof import("../app/components/Domain/Cookbook/CookbookPage.vue")['default']>
export const LazyGroupDataPage: LazyComponent<typeof import("../app/components/Domain/Group/GroupDataPage.vue")['default']>
export const LazyGroupExportData: LazyComponent<typeof import("../app/components/Domain/Group/GroupExportData.vue")['default']>
export const LazyGroupPreferencesEditor: LazyComponent<typeof import("../app/components/Domain/Group/GroupPreferencesEditor.vue")['default']>
export const LazyGroupMealPlanDayContextMenu: LazyComponent<typeof import("../app/components/Domain/Household/GroupMealPlanDayContextMenu.vue")['default']>
export const LazyGroupMealPlanRuleForm: LazyComponent<typeof import("../app/components/Domain/Household/GroupMealPlanRuleForm.vue")['default']>
export const LazyGroupWebhookEditor: LazyComponent<typeof import("../app/components/Domain/Household/GroupWebhookEditor.vue")['default']>
export const LazyHouseholdPreferencesEditor: LazyComponent<typeof import("../app/components/Domain/Household/HouseholdPreferencesEditor.vue")['default']>
export const LazyQueryFilterBuilder: LazyComponent<typeof import("../app/components/Domain/QueryFilterBuilder.vue")['default']>
export const LazyRecipeActionMenu: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeActionMenu.vue")['default']>
export const LazyRecipeAssets: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeAssets.vue")['default']>
export const LazyRecipeCard: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeCard.vue")['default']>
export const LazyRecipeCardImage: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeCardImage.vue")['default']>
export const LazyRecipeCardMobile: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeCardMobile.vue")['default']>
export const LazyRecipeCardRating: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeCardRating.vue")['default']>
export const LazyRecipeCardSection: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeCardSection.vue")['default']>
export const LazyRecipeChips: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeChips.vue")['default']>
export const LazyRecipeContextMenu: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeContextMenu/RecipeContextMenu.vue")['default']>
export const LazyRecipeContextMenuContent: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeContextMenu/RecipeContextMenuContent.vue")['default']>
export const LazyRecipeDataAliasManagerDialog: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeDataAliasManagerDialog.vue")['default']>
export const LazyRecipeDataTable: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeDataTable.vue")['default']>
export const LazyRecipeDialogAddToShoppingList: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeDialogAddToShoppingList.vue")['default']>
export const LazyRecipeDialogBulkAdd: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeDialogBulkAdd.vue")['default']>
export const LazyRecipeDialogPrintPreferences: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeDialogPrintPreferences.vue")['default']>
export const LazyRecipeDialogSearch: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeDialogSearch.vue")['default']>
export const LazyRecipeDialogShare: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeDialogShare.vue")['default']>
export const LazyRecipeExplorerPage: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeExplorerPage/RecipeExplorerPage.vue")['default']>
export const LazyRecipeExplorerPageSearch: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeExplorerPage/RecipeExplorerPageParts/RecipeExplorerPageSearch.vue")['default']>
export const LazyRecipeExplorerPageSearchFilters: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeExplorerPage/RecipeExplorerPageParts/RecipeExplorerPageSearchFilters.vue")['default']>
export const LazyRecipeFavoriteBadge: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeFavoriteBadge.vue")['default']>
export const LazyRecipeImageUploadBtn: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeImageUploadBtn.vue")['default']>
export const LazyRecipeIngredientEditor: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeIngredientEditor.vue")['default']>
export const LazyRecipeIngredientHtml: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeIngredientHtml.vue")['default']>
export const LazyRecipeIngredientListItem: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeIngredientListItem.vue")['default']>
export const LazyRecipeIngredients: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeIngredients.vue")['default']>
export const LazyRecipeLastMade: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeLastMade.vue")['default']>
export const LazyRecipeList: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeList.vue")['default']>
export const LazyRecipeNotes: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeNotes.vue")['default']>
export const LazyRecipeNutrition: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeNutrition.vue")['default']>
export const LazyRecipeOrganizerDialog: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeOrganizerDialog.vue")['default']>
export const LazyRecipeOrganizerPage: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeOrganizerPage.vue")['default']>
export const LazyRecipeOrganizerSelector: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeOrganizerSelector.vue")['default']>
export const LazyRecipePage: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePage/RecipePage.vue")['default']>
export const LazyRecipePageComments: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageComments.vue")['default']>
export const LazyRecipePageEditorToolbar: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageEditorToolbar.vue")['default']>
export const LazyRecipePageFooter: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageFooter.vue")['default']>
export const LazyRecipePageHeader: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageHeader.vue")['default']>
export const LazyRecipePageInfoCard: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoCard.vue")['default']>
export const LazyRecipePageInfoCardImage: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoCardImage.vue")['default']>
export const LazyRecipePageInfoEditor: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoEditor.vue")['default']>
export const LazyRecipePageIngredientEditor: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientEditor.vue")['default']>
export const LazyRecipePageIngredientToolsView: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientToolsView.vue")['default']>
export const LazyRecipePageInstructions: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInstructions.vue")['default']>
export const LazyRecipePageOrganizers: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageOrganizers.vue")['default']>
export const LazyRecipePageParseDialog: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageParseDialog.vue")['default']>
export const LazyRecipePageScale: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageScale.vue")['default']>
export const LazyRecipePrintContainer: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePrintContainer.vue")['default']>
export const LazyRecipePrintView: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipePrintView.vue")['default']>
export const LazyRecipeRating: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeRating.vue")['default']>
export const LazyRecipeScaleEditButton: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeScaleEditButton.vue")['default']>
export const LazyRecipeSettingsMenu: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeSettingsMenu.vue")['default']>
export const LazyRecipeSettingsSwitches: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeSettingsSwitches.vue")['default']>
export const LazyRecipeSuggestion: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeSuggestion.vue")['default']>
export const LazyRecipeTimeCard: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeTimeCard.vue")['default']>
export const LazyRecipeTimeline: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeTimeline.vue")['default']>
export const LazyRecipeTimelineBadge: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeTimelineBadge.vue")['default']>
export const LazyRecipeTimelineContextMenu: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeTimelineContextMenu.vue")['default']>
export const LazyRecipeTimelineItem: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeTimelineItem.vue")['default']>
export const LazyRecipeYield: LazyComponent<typeof import("../app/components/Domain/Recipe/RecipeYield.vue")['default']>
export const LazySearchFilter: LazyComponent<typeof import("../app/components/Domain/SearchFilter.vue")['default']>
export const LazyMultiPurposeLabel: LazyComponent<typeof import("../app/components/Domain/ShoppingList/MultiPurposeLabel.vue")['default']>
export const LazyMultiPurposeLabelSection: LazyComponent<typeof import("../app/components/Domain/ShoppingList/MultiPurposeLabelSection.vue")['default']>
export const LazyShoppingListItem: LazyComponent<typeof import("../app/components/Domain/ShoppingList/ShoppingListItem.vue")['default']>
export const LazyShoppingListItemEditor: LazyComponent<typeof import("../app/components/Domain/ShoppingList/ShoppingListItemEditor.vue")['default']>
export const LazyUserAvatar: LazyComponent<typeof import("../app/components/Domain/User/UserAvatar.vue")['default']>
export const LazyUserInviteDialog: LazyComponent<typeof import("../app/components/Domain/User/UserInviteDialog.vue")['default']>
export const LazyUserPasswordStrength: LazyComponent<typeof import("../app/components/Domain/User/UserPasswordStrength.vue")['default']>
export const LazyUserProfileLinkCard: LazyComponent<typeof import("../app/components/Domain/User/UserProfileLinkCard.vue")['default']>
export const LazyUserRegistrationForm: LazyComponent<typeof import("../app/components/Domain/User/UserRegistrationForm.vue")['default']>
export const LazyDefaultLayout: LazyComponent<typeof import("../app/components/Layout/DefaultLayout.vue")['default']>
export const LazyAppFooter: LazyComponent<typeof import("../app/components/Layout/LayoutParts/AppFooter.vue")['default']>
export const LazyAppHeader: LazyComponent<typeof import("../app/components/Layout/LayoutParts/AppHeader.vue")['default']>
export const LazyAppScrollToTop: LazyComponent<typeof import("../app/components/Layout/LayoutParts/AppScrollToTop.vue")['default']>
export const LazyAppSidebar: LazyComponent<typeof import("../app/components/Layout/LayoutParts/AppSidebar.vue")['default']>
export const LazyTheSnackbar: LazyComponent<typeof import("../app/components/Layout/LayoutParts/TheSnackbar.vue")['default']>
export const LazyAdvancedOnly: LazyComponent<typeof import("../app/components/global/AdvancedOnly.vue")['default']>
export const LazyAppButtonCopy: LazyComponent<typeof import("../app/components/global/AppButtonCopy.vue")['default']>
export const LazyAppButtonUpload: LazyComponent<typeof import("../app/components/global/AppButtonUpload.vue")['default']>
export const LazyAppLoader: LazyComponent<typeof import("../app/components/global/AppLoader.vue")['default']>
export const LazyAppLogo: LazyComponent<typeof import("../app/components/global/AppLogo.vue")['default']>
export const LazyAppToolbar: LazyComponent<typeof import("../app/components/global/AppToolbar.vue")['default']>
export const LazyAutoForm: LazyComponent<typeof import("../app/components/global/AutoForm.vue")['default']>
export const LazyBannerExperimental: LazyComponent<typeof import("../app/components/global/BannerExperimental.vue")['default']>
export const LazyBannerWarning: LazyComponent<typeof import("../app/components/global/BannerWarning.vue")['default']>
export const LazyBaseButton: LazyComponent<typeof import("../app/components/global/BaseButton.vue")['default']>
export const LazyBaseButtonGroup: LazyComponent<typeof import("../app/components/global/BaseButtonGroup.vue")['default']>
export const LazyBaseCardSectionTitle: LazyComponent<typeof import("../app/components/global/BaseCardSectionTitle.vue")['default']>
export const LazyBaseDialog: LazyComponent<typeof import("../app/components/global/BaseDialog.vue")['default']>
export const LazyBaseDivider: LazyComponent<typeof import("../app/components/global/BaseDivider.vue")['default']>
export const LazyBaseExpansionPanels: LazyComponent<typeof import("../app/components/global/BaseExpansionPanels.vue")['default']>
export const LazyBaseOverflowButton: LazyComponent<typeof import("../app/components/global/BaseOverflowButton.vue")['default']>
export const LazyBasePageTitle: LazyComponent<typeof import("../app/components/global/BasePageTitle.vue")['default']>
export const LazyButtonLink: LazyComponent<typeof import("../app/components/global/ButtonLink.vue")['default']>
export const LazyContextMenu: LazyComponent<typeof import("../app/components/global/ContextMenu.vue")['default']>
export const LazyCrudTable: LazyComponent<typeof import("../app/components/global/CrudTable.vue")['default']>
export const LazyDevDumpJson: LazyComponent<typeof import("../app/components/global/DevDumpJson.vue")['default']>
export const LazyDocLink: LazyComponent<typeof import("../app/components/global/DocLink.vue")['default']>
export const LazyDropZone: LazyComponent<typeof import("../app/components/global/DropZone.vue")['default']>
export const LazyHelpIcon: LazyComponent<typeof import("../app/components/global/HelpIcon.vue")['default']>
export const LazyImageCropper: LazyComponent<typeof import("../app/components/global/ImageCropper.vue")['default']>
export const LazyInputColor: LazyComponent<typeof import("../app/components/global/InputColor.vue")['default']>
export const LazyInputLabelType: LazyComponent<typeof import("../app/components/global/InputLabelType.vue")['default']>
export const LazyLanguageDialog: LazyComponent<typeof import("../app/components/global/LanguageDialog.vue")['default']>
export const LazyMarkdownEditor: LazyComponent<typeof import("../app/components/global/MarkdownEditor.vue")['default']>
export const LazyRecipeJsonEditor: LazyComponent<typeof import("../app/components/global/RecipeJsonEditor.vue")['default']>
export const LazyReportTable: LazyComponent<typeof import("../app/components/global/ReportTable.vue")['default']>
export const LazySafeMarkdown: LazyComponent<typeof import("../app/components/global/SafeMarkdown.vue")['default']>
export const LazyStatsCards: LazyComponent<typeof import("../app/components/global/StatsCards.vue")['default']>
export const LazyToggleState: LazyComponent<typeof import("../app/components/global/ToggleState.vue")['default']>
export const LazyWakelockSwitch: LazyComponent<typeof import("../app/components/global/WakelockSwitch.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyVitePwaManifest: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
export const LazyNuxtPwaManifest: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
export const LazyNuxtPwaAssets: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']>
export const LazyPwaAppleImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']>
export const LazyPwaAppleSplashScreenImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']>
export const LazyPwaFaviconImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']>
export const LazyPwaMaskableImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']>
export const LazyPwaTransparentImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']>
export const LazyNuxtLinkLocale: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
export const LazySwitchLocalePathLink: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
