export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData, createUseAsyncData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch, createUseFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useAnnouncer } from '#app/composables/announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, useCssVars, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta, PageMeta } from '#app/composables/pages';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useAnnouncements, AnnouncementMeta, Announcement } from '../app/composables/use-announcements';
export { useAuthBackend } from '../app/composables/use-auth-backend';
export { useBackups } from '../app/composables/use-backups';
export { useContextPresets, ContextMenuItem, ContextMenuPresets } from '../app/composables/use-context-presents';
export { useCopy, useCopyList } from '../app/composables/use-copy';
export { default as useDefaultActivity, DEFAULT_ACTIVITY } from '../app/composables/use-default-activity';
export { useGlobalI18n } from '../app/composables/use-global-i18n';
export { useCookbook } from '../app/composables/use-group-cookbooks';
export { usePlanTypeOptions, getEntryTypeText, useMealplans, DateRange } from '../app/composables/use-group-mealplan';
export { useGroupRecipeActionData, useGroupRecipeActions } from '../app/composables/use-group-recipe-actions';
export { useGroupWebhooks, timeUTC, timeUTCToLocal, timeLocalToUTC } from '../app/composables/use-group-webhooks';
export { useGroupSelf, useGroups } from '../app/composables/use-groups';
export { useHouseholdSelf, useAdminHouseholds } from '../app/composables/use-households';
export { useLoggedInState } from '../app/composables/use-logged-in-state';
export { useMealieAuth } from '../app/composables/use-mealie-auth';
export { useNavigationWarning } from '../app/composables/use-navigation-warning';
export { useNewRecipeOptions, UseNewRecipeOptionsProps } from '../app/composables/use-new-recipe-options';
export { usePasswordField, usePasswordStrength } from '../app/composables/use-passwords';
export { useQueryFilterBuilder, FieldLogicalOperator, FieldRelationalOperator, FieldPlaceholderKeyword, OrganizerBase, FieldType, FieldValue, SelectableItem, FieldDefinition, Field } from '../app/composables/use-query-filter-builder';
export { useRecipeExplorerSearch, clearRecipeExplorerSearchState } from '../app/composables/use-recipe-explorer-search';
export { useRouterQuery, useRouteQuery } from '../app/composables/use-router';
export { useScrollPosition } from '../app/composables/use-scroll-position';
export { useSearch, IAlias, ISearchableItem, ISearchOptions } from '../app/composables/use-search';
export { useShoppingListItemActions } from '../app/composables/use-shopping-list-item-actions';
export { getTextColor } from '../app/composables/use-text-color';
export { toastAlert, toastLoading, loader, alert } from '../app/composables/use-toast';
export { useAllUsers, useUser } from '../app/composables/use-user';
export { useToggleDarkMode, useAsyncKey, titleCase, normalize, normalizeFilter, uuid4, deepCopy, downloadAsJson } from '../app/composables/use-utils';
export { validators, useAsyncValidator } from '../app/composables/use-validators';
export { usePWA, useTransparentPwaIcon, useMaskablePwaIcon, useFaviconPwaIcon, useApplePwaIcon, useAppleSplashScreenPwaIcon } from '../node_modules/@vite-pwa/nuxt/dist/runtime/composables/index';
export { useI18n } from '../node_modules/vue-i18n/dist/vue-i18n';
export { useRouteBaseName, useLocalePath, useLocaleRoute, useSwitchLocalePath, useLocaleHead, useBrowserLocale, useCookieLocale, useSetI18nParams, defineI18nRoute, defineI18nLocale, defineI18nConfig } from '../node_modules/@nuxtjs/i18n/dist/runtime/composables/index';
export { useDate, useLocale, useDefaults, useDisplay, useLayout, useRtl, useTheme, useGoTo, useHotkey, useMask } from 'vuetify';