
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  EndPageContent: typeof import("../../app/components/Domain/Admin/Setup/EndPageContent.vue")['default']
  AnnouncementDialog: typeof import("../../app/components/Domain/Announcement/AnnouncementDialog.vue")['default']
  "202603271Welcome": typeof import("../../app/components/Domain/Announcement/Announcements/2026-03-27_1_welcome.vue")['default']
  CookbookEditor: typeof import("../../app/components/Domain/Cookbook/CookbookEditor.vue")['default']
  CookbookPage: typeof import("../../app/components/Domain/Cookbook/CookbookPage.vue")['default']
  GroupDataPage: typeof import("../../app/components/Domain/Group/GroupDataPage.vue")['default']
  GroupExportData: typeof import("../../app/components/Domain/Group/GroupExportData.vue")['default']
  GroupPreferencesEditor: typeof import("../../app/components/Domain/Group/GroupPreferencesEditor.vue")['default']
  GroupMealPlanDayContextMenu: typeof import("../../app/components/Domain/Household/GroupMealPlanDayContextMenu.vue")['default']
  GroupMealPlanRuleForm: typeof import("../../app/components/Domain/Household/GroupMealPlanRuleForm.vue")['default']
  GroupWebhookEditor: typeof import("../../app/components/Domain/Household/GroupWebhookEditor.vue")['default']
  HouseholdPreferencesEditor: typeof import("../../app/components/Domain/Household/HouseholdPreferencesEditor.vue")['default']
  QueryFilterBuilder: typeof import("../../app/components/Domain/QueryFilterBuilder.vue")['default']
  RecipeActionMenu: typeof import("../../app/components/Domain/Recipe/RecipeActionMenu.vue")['default']
  RecipeAssets: typeof import("../../app/components/Domain/Recipe/RecipeAssets.vue")['default']
  RecipeCard: typeof import("../../app/components/Domain/Recipe/RecipeCard.vue")['default']
  RecipeCardImage: typeof import("../../app/components/Domain/Recipe/RecipeCardImage.vue")['default']
  RecipeCardMobile: typeof import("../../app/components/Domain/Recipe/RecipeCardMobile.vue")['default']
  RecipeCardRating: typeof import("../../app/components/Domain/Recipe/RecipeCardRating.vue")['default']
  RecipeCardSection: typeof import("../../app/components/Domain/Recipe/RecipeCardSection.vue")['default']
  RecipeChips: typeof import("../../app/components/Domain/Recipe/RecipeChips.vue")['default']
  RecipeContextMenu: typeof import("../../app/components/Domain/Recipe/RecipeContextMenu/RecipeContextMenu.vue")['default']
  RecipeContextMenuContent: typeof import("../../app/components/Domain/Recipe/RecipeContextMenu/RecipeContextMenuContent.vue")['default']
  RecipeDataAliasManagerDialog: typeof import("../../app/components/Domain/Recipe/RecipeDataAliasManagerDialog.vue")['default']
  RecipeDataTable: typeof import("../../app/components/Domain/Recipe/RecipeDataTable.vue")['default']
  RecipeDialogAddToShoppingList: typeof import("../../app/components/Domain/Recipe/RecipeDialogAddToShoppingList.vue")['default']
  RecipeDialogBulkAdd: typeof import("../../app/components/Domain/Recipe/RecipeDialogBulkAdd.vue")['default']
  RecipeDialogPrintPreferences: typeof import("../../app/components/Domain/Recipe/RecipeDialogPrintPreferences.vue")['default']
  RecipeDialogSearch: typeof import("../../app/components/Domain/Recipe/RecipeDialogSearch.vue")['default']
  RecipeDialogShare: typeof import("../../app/components/Domain/Recipe/RecipeDialogShare.vue")['default']
  RecipeExplorerPage: typeof import("../../app/components/Domain/Recipe/RecipeExplorerPage/RecipeExplorerPage.vue")['default']
  RecipeExplorerPageSearch: typeof import("../../app/components/Domain/Recipe/RecipeExplorerPage/RecipeExplorerPageParts/RecipeExplorerPageSearch.vue")['default']
  RecipeExplorerPageSearchFilters: typeof import("../../app/components/Domain/Recipe/RecipeExplorerPage/RecipeExplorerPageParts/RecipeExplorerPageSearchFilters.vue")['default']
  RecipeFavoriteBadge: typeof import("../../app/components/Domain/Recipe/RecipeFavoriteBadge.vue")['default']
  RecipeImageUploadBtn: typeof import("../../app/components/Domain/Recipe/RecipeImageUploadBtn.vue")['default']
  RecipeIngredientEditor: typeof import("../../app/components/Domain/Recipe/RecipeIngredientEditor.vue")['default']
  RecipeIngredientHtml: typeof import("../../app/components/Domain/Recipe/RecipeIngredientHtml.vue")['default']
  RecipeIngredientListItem: typeof import("../../app/components/Domain/Recipe/RecipeIngredientListItem.vue")['default']
  RecipeIngredients: typeof import("../../app/components/Domain/Recipe/RecipeIngredients.vue")['default']
  RecipeLastMade: typeof import("../../app/components/Domain/Recipe/RecipeLastMade.vue")['default']
  RecipeList: typeof import("../../app/components/Domain/Recipe/RecipeList.vue")['default']
  RecipeNotes: typeof import("../../app/components/Domain/Recipe/RecipeNotes.vue")['default']
  RecipeNutrition: typeof import("../../app/components/Domain/Recipe/RecipeNutrition.vue")['default']
  RecipeOrganizerDialog: typeof import("../../app/components/Domain/Recipe/RecipeOrganizerDialog.vue")['default']
  RecipeOrganizerPage: typeof import("../../app/components/Domain/Recipe/RecipeOrganizerPage.vue")['default']
  RecipeOrganizerSelector: typeof import("../../app/components/Domain/Recipe/RecipeOrganizerSelector.vue")['default']
  RecipePage: typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePage.vue")['default']
  RecipePageComments: typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageComments.vue")['default']
  RecipePageEditorToolbar: typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageEditorToolbar.vue")['default']
  RecipePageFooter: typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageFooter.vue")['default']
  RecipePageHeader: typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageHeader.vue")['default']
  RecipePageInfoCard: typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoCard.vue")['default']
  RecipePageInfoCardImage: typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoCardImage.vue")['default']
  RecipePageInfoEditor: typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoEditor.vue")['default']
  RecipePageIngredientEditor: typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientEditor.vue")['default']
  RecipePageIngredientToolsView: typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientToolsView.vue")['default']
  RecipePageInstructions: typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInstructions.vue")['default']
  RecipePageOrganizers: typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageOrganizers.vue")['default']
  RecipePageParseDialog: typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageParseDialog.vue")['default']
  RecipePageScale: typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageScale.vue")['default']
  RecipePrintContainer: typeof import("../../app/components/Domain/Recipe/RecipePrintContainer.vue")['default']
  RecipePrintView: typeof import("../../app/components/Domain/Recipe/RecipePrintView.vue")['default']
  RecipeRating: typeof import("../../app/components/Domain/Recipe/RecipeRating.vue")['default']
  RecipeScaleEditButton: typeof import("../../app/components/Domain/Recipe/RecipeScaleEditButton.vue")['default']
  RecipeSettingsMenu: typeof import("../../app/components/Domain/Recipe/RecipeSettingsMenu.vue")['default']
  RecipeSettingsSwitches: typeof import("../../app/components/Domain/Recipe/RecipeSettingsSwitches.vue")['default']
  RecipeSuggestion: typeof import("../../app/components/Domain/Recipe/RecipeSuggestion.vue")['default']
  RecipeTimeCard: typeof import("../../app/components/Domain/Recipe/RecipeTimeCard.vue")['default']
  RecipeTimeline: typeof import("../../app/components/Domain/Recipe/RecipeTimeline.vue")['default']
  RecipeTimelineBadge: typeof import("../../app/components/Domain/Recipe/RecipeTimelineBadge.vue")['default']
  RecipeTimelineContextMenu: typeof import("../../app/components/Domain/Recipe/RecipeTimelineContextMenu.vue")['default']
  RecipeTimelineItem: typeof import("../../app/components/Domain/Recipe/RecipeTimelineItem.vue")['default']
  RecipeYield: typeof import("../../app/components/Domain/Recipe/RecipeYield.vue")['default']
  SearchFilter: typeof import("../../app/components/Domain/SearchFilter.vue")['default']
  MultiPurposeLabel: typeof import("../../app/components/Domain/ShoppingList/MultiPurposeLabel.vue")['default']
  MultiPurposeLabelSection: typeof import("../../app/components/Domain/ShoppingList/MultiPurposeLabelSection.vue")['default']
  ShoppingListItem: typeof import("../../app/components/Domain/ShoppingList/ShoppingListItem.vue")['default']
  ShoppingListItemEditor: typeof import("../../app/components/Domain/ShoppingList/ShoppingListItemEditor.vue")['default']
  UserAvatar: typeof import("../../app/components/Domain/User/UserAvatar.vue")['default']
  UserInviteDialog: typeof import("../../app/components/Domain/User/UserInviteDialog.vue")['default']
  UserPasswordStrength: typeof import("../../app/components/Domain/User/UserPasswordStrength.vue")['default']
  UserProfileLinkCard: typeof import("../../app/components/Domain/User/UserProfileLinkCard.vue")['default']
  UserRegistrationForm: typeof import("../../app/components/Domain/User/UserRegistrationForm.vue")['default']
  DefaultLayout: typeof import("../../app/components/Layout/DefaultLayout.vue")['default']
  AppFooter: typeof import("../../app/components/Layout/LayoutParts/AppFooter.vue")['default']
  AppHeader: typeof import("../../app/components/Layout/LayoutParts/AppHeader.vue")['default']
  AppScrollToTop: typeof import("../../app/components/Layout/LayoutParts/AppScrollToTop.vue")['default']
  AppSidebar: typeof import("../../app/components/Layout/LayoutParts/AppSidebar.vue")['default']
  TheSnackbar: typeof import("../../app/components/Layout/LayoutParts/TheSnackbar.vue")['default']
  AdvancedOnly: typeof import("../../app/components/global/AdvancedOnly.vue")['default']
  AppButtonCopy: typeof import("../../app/components/global/AppButtonCopy.vue")['default']
  AppButtonUpload: typeof import("../../app/components/global/AppButtonUpload.vue")['default']
  AppLoader: typeof import("../../app/components/global/AppLoader.vue")['default']
  AppLogo: typeof import("../../app/components/global/AppLogo.vue")['default']
  AppToolbar: typeof import("../../app/components/global/AppToolbar.vue")['default']
  AutoForm: typeof import("../../app/components/global/AutoForm.vue")['default']
  BannerExperimental: typeof import("../../app/components/global/BannerExperimental.vue")['default']
  BannerWarning: typeof import("../../app/components/global/BannerWarning.vue")['default']
  BaseButton: typeof import("../../app/components/global/BaseButton.vue")['default']
  BaseButtonGroup: typeof import("../../app/components/global/BaseButtonGroup.vue")['default']
  BaseCardSectionTitle: typeof import("../../app/components/global/BaseCardSectionTitle.vue")['default']
  BaseDialog: typeof import("../../app/components/global/BaseDialog.vue")['default']
  BaseDivider: typeof import("../../app/components/global/BaseDivider.vue")['default']
  BaseExpansionPanels: typeof import("../../app/components/global/BaseExpansionPanels.vue")['default']
  BaseOverflowButton: typeof import("../../app/components/global/BaseOverflowButton.vue")['default']
  BasePageTitle: typeof import("../../app/components/global/BasePageTitle.vue")['default']
  ButtonLink: typeof import("../../app/components/global/ButtonLink.vue")['default']
  ContextMenu: typeof import("../../app/components/global/ContextMenu.vue")['default']
  CrudTable: typeof import("../../app/components/global/CrudTable.vue")['default']
  DevDumpJson: typeof import("../../app/components/global/DevDumpJson.vue")['default']
  DocLink: typeof import("../../app/components/global/DocLink.vue")['default']
  DropZone: typeof import("../../app/components/global/DropZone.vue")['default']
  HelpIcon: typeof import("../../app/components/global/HelpIcon.vue")['default']
  ImageCropper: typeof import("../../app/components/global/ImageCropper.vue")['default']
  InputColor: typeof import("../../app/components/global/InputColor.vue")['default']
  InputLabelType: typeof import("../../app/components/global/InputLabelType.vue")['default']
  LanguageDialog: typeof import("../../app/components/global/LanguageDialog.vue")['default']
  MarkdownEditor: typeof import("../../app/components/global/MarkdownEditor.vue")['default']
  RecipeJsonEditor: typeof import("../../app/components/global/RecipeJsonEditor.vue")['default']
  ReportTable: typeof import("../../app/components/global/ReportTable.vue")['default']
  SafeMarkdown: typeof import("../../app/components/global/SafeMarkdown.vue")['default']
  StatsCards: typeof import("../../app/components/global/StatsCards.vue")['default']
  ToggleState: typeof import("../../app/components/global/ToggleState.vue")['default']
  WakelockSwitch: typeof import("../../app/components/global/WakelockSwitch.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  VitePwaManifest: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
  NuxtPwaManifest: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
  NuxtPwaAssets: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
  PwaAppleImage: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
  PwaAppleSplashScreenImage: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
  PwaFaviconImage: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
  PwaMaskableImage: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
  PwaTransparentImage: typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
  NuxtLinkLocale: typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
  SwitchLocalePathLink: typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyEndPageContent: LazyComponent<typeof import("../../app/components/Domain/Admin/Setup/EndPageContent.vue")['default']>
  LazyAnnouncementDialog: LazyComponent<typeof import("../../app/components/Domain/Announcement/AnnouncementDialog.vue")['default']>
  Lazy202603271Welcome: LazyComponent<typeof import("../../app/components/Domain/Announcement/Announcements/2026-03-27_1_welcome.vue")['default']>
  LazyCookbookEditor: LazyComponent<typeof import("../../app/components/Domain/Cookbook/CookbookEditor.vue")['default']>
  LazyCookbookPage: LazyComponent<typeof import("../../app/components/Domain/Cookbook/CookbookPage.vue")['default']>
  LazyGroupDataPage: LazyComponent<typeof import("../../app/components/Domain/Group/GroupDataPage.vue")['default']>
  LazyGroupExportData: LazyComponent<typeof import("../../app/components/Domain/Group/GroupExportData.vue")['default']>
  LazyGroupPreferencesEditor: LazyComponent<typeof import("../../app/components/Domain/Group/GroupPreferencesEditor.vue")['default']>
  LazyGroupMealPlanDayContextMenu: LazyComponent<typeof import("../../app/components/Domain/Household/GroupMealPlanDayContextMenu.vue")['default']>
  LazyGroupMealPlanRuleForm: LazyComponent<typeof import("../../app/components/Domain/Household/GroupMealPlanRuleForm.vue")['default']>
  LazyGroupWebhookEditor: LazyComponent<typeof import("../../app/components/Domain/Household/GroupWebhookEditor.vue")['default']>
  LazyHouseholdPreferencesEditor: LazyComponent<typeof import("../../app/components/Domain/Household/HouseholdPreferencesEditor.vue")['default']>
  LazyQueryFilterBuilder: LazyComponent<typeof import("../../app/components/Domain/QueryFilterBuilder.vue")['default']>
  LazyRecipeActionMenu: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeActionMenu.vue")['default']>
  LazyRecipeAssets: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeAssets.vue")['default']>
  LazyRecipeCard: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeCard.vue")['default']>
  LazyRecipeCardImage: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeCardImage.vue")['default']>
  LazyRecipeCardMobile: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeCardMobile.vue")['default']>
  LazyRecipeCardRating: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeCardRating.vue")['default']>
  LazyRecipeCardSection: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeCardSection.vue")['default']>
  LazyRecipeChips: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeChips.vue")['default']>
  LazyRecipeContextMenu: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeContextMenu/RecipeContextMenu.vue")['default']>
  LazyRecipeContextMenuContent: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeContextMenu/RecipeContextMenuContent.vue")['default']>
  LazyRecipeDataAliasManagerDialog: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeDataAliasManagerDialog.vue")['default']>
  LazyRecipeDataTable: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeDataTable.vue")['default']>
  LazyRecipeDialogAddToShoppingList: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeDialogAddToShoppingList.vue")['default']>
  LazyRecipeDialogBulkAdd: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeDialogBulkAdd.vue")['default']>
  LazyRecipeDialogPrintPreferences: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeDialogPrintPreferences.vue")['default']>
  LazyRecipeDialogSearch: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeDialogSearch.vue")['default']>
  LazyRecipeDialogShare: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeDialogShare.vue")['default']>
  LazyRecipeExplorerPage: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeExplorerPage/RecipeExplorerPage.vue")['default']>
  LazyRecipeExplorerPageSearch: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeExplorerPage/RecipeExplorerPageParts/RecipeExplorerPageSearch.vue")['default']>
  LazyRecipeExplorerPageSearchFilters: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeExplorerPage/RecipeExplorerPageParts/RecipeExplorerPageSearchFilters.vue")['default']>
  LazyRecipeFavoriteBadge: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeFavoriteBadge.vue")['default']>
  LazyRecipeImageUploadBtn: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeImageUploadBtn.vue")['default']>
  LazyRecipeIngredientEditor: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeIngredientEditor.vue")['default']>
  LazyRecipeIngredientHtml: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeIngredientHtml.vue")['default']>
  LazyRecipeIngredientListItem: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeIngredientListItem.vue")['default']>
  LazyRecipeIngredients: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeIngredients.vue")['default']>
  LazyRecipeLastMade: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeLastMade.vue")['default']>
  LazyRecipeList: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeList.vue")['default']>
  LazyRecipeNotes: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeNotes.vue")['default']>
  LazyRecipeNutrition: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeNutrition.vue")['default']>
  LazyRecipeOrganizerDialog: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeOrganizerDialog.vue")['default']>
  LazyRecipeOrganizerPage: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeOrganizerPage.vue")['default']>
  LazyRecipeOrganizerSelector: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeOrganizerSelector.vue")['default']>
  LazyRecipePage: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePage.vue")['default']>
  LazyRecipePageComments: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageComments.vue")['default']>
  LazyRecipePageEditorToolbar: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageEditorToolbar.vue")['default']>
  LazyRecipePageFooter: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageFooter.vue")['default']>
  LazyRecipePageHeader: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageHeader.vue")['default']>
  LazyRecipePageInfoCard: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoCard.vue")['default']>
  LazyRecipePageInfoCardImage: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoCardImage.vue")['default']>
  LazyRecipePageInfoEditor: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInfoEditor.vue")['default']>
  LazyRecipePageIngredientEditor: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientEditor.vue")['default']>
  LazyRecipePageIngredientToolsView: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageIngredientToolsView.vue")['default']>
  LazyRecipePageInstructions: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageInstructions.vue")['default']>
  LazyRecipePageOrganizers: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageOrganizers.vue")['default']>
  LazyRecipePageParseDialog: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageParseDialog.vue")['default']>
  LazyRecipePageScale: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageScale.vue")['default']>
  LazyRecipePrintContainer: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePrintContainer.vue")['default']>
  LazyRecipePrintView: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipePrintView.vue")['default']>
  LazyRecipeRating: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeRating.vue")['default']>
  LazyRecipeScaleEditButton: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeScaleEditButton.vue")['default']>
  LazyRecipeSettingsMenu: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeSettingsMenu.vue")['default']>
  LazyRecipeSettingsSwitches: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeSettingsSwitches.vue")['default']>
  LazyRecipeSuggestion: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeSuggestion.vue")['default']>
  LazyRecipeTimeCard: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeTimeCard.vue")['default']>
  LazyRecipeTimeline: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeTimeline.vue")['default']>
  LazyRecipeTimelineBadge: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeTimelineBadge.vue")['default']>
  LazyRecipeTimelineContextMenu: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeTimelineContextMenu.vue")['default']>
  LazyRecipeTimelineItem: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeTimelineItem.vue")['default']>
  LazyRecipeYield: LazyComponent<typeof import("../../app/components/Domain/Recipe/RecipeYield.vue")['default']>
  LazySearchFilter: LazyComponent<typeof import("../../app/components/Domain/SearchFilter.vue")['default']>
  LazyMultiPurposeLabel: LazyComponent<typeof import("../../app/components/Domain/ShoppingList/MultiPurposeLabel.vue")['default']>
  LazyMultiPurposeLabelSection: LazyComponent<typeof import("../../app/components/Domain/ShoppingList/MultiPurposeLabelSection.vue")['default']>
  LazyShoppingListItem: LazyComponent<typeof import("../../app/components/Domain/ShoppingList/ShoppingListItem.vue")['default']>
  LazyShoppingListItemEditor: LazyComponent<typeof import("../../app/components/Domain/ShoppingList/ShoppingListItemEditor.vue")['default']>
  LazyUserAvatar: LazyComponent<typeof import("../../app/components/Domain/User/UserAvatar.vue")['default']>
  LazyUserInviteDialog: LazyComponent<typeof import("../../app/components/Domain/User/UserInviteDialog.vue")['default']>
  LazyUserPasswordStrength: LazyComponent<typeof import("../../app/components/Domain/User/UserPasswordStrength.vue")['default']>
  LazyUserProfileLinkCard: LazyComponent<typeof import("../../app/components/Domain/User/UserProfileLinkCard.vue")['default']>
  LazyUserRegistrationForm: LazyComponent<typeof import("../../app/components/Domain/User/UserRegistrationForm.vue")['default']>
  LazyDefaultLayout: LazyComponent<typeof import("../../app/components/Layout/DefaultLayout.vue")['default']>
  LazyAppFooter: LazyComponent<typeof import("../../app/components/Layout/LayoutParts/AppFooter.vue")['default']>
  LazyAppHeader: LazyComponent<typeof import("../../app/components/Layout/LayoutParts/AppHeader.vue")['default']>
  LazyAppScrollToTop: LazyComponent<typeof import("../../app/components/Layout/LayoutParts/AppScrollToTop.vue")['default']>
  LazyAppSidebar: LazyComponent<typeof import("../../app/components/Layout/LayoutParts/AppSidebar.vue")['default']>
  LazyTheSnackbar: LazyComponent<typeof import("../../app/components/Layout/LayoutParts/TheSnackbar.vue")['default']>
  LazyAdvancedOnly: LazyComponent<typeof import("../../app/components/global/AdvancedOnly.vue")['default']>
  LazyAppButtonCopy: LazyComponent<typeof import("../../app/components/global/AppButtonCopy.vue")['default']>
  LazyAppButtonUpload: LazyComponent<typeof import("../../app/components/global/AppButtonUpload.vue")['default']>
  LazyAppLoader: LazyComponent<typeof import("../../app/components/global/AppLoader.vue")['default']>
  LazyAppLogo: LazyComponent<typeof import("../../app/components/global/AppLogo.vue")['default']>
  LazyAppToolbar: LazyComponent<typeof import("../../app/components/global/AppToolbar.vue")['default']>
  LazyAutoForm: LazyComponent<typeof import("../../app/components/global/AutoForm.vue")['default']>
  LazyBannerExperimental: LazyComponent<typeof import("../../app/components/global/BannerExperimental.vue")['default']>
  LazyBannerWarning: LazyComponent<typeof import("../../app/components/global/BannerWarning.vue")['default']>
  LazyBaseButton: LazyComponent<typeof import("../../app/components/global/BaseButton.vue")['default']>
  LazyBaseButtonGroup: LazyComponent<typeof import("../../app/components/global/BaseButtonGroup.vue")['default']>
  LazyBaseCardSectionTitle: LazyComponent<typeof import("../../app/components/global/BaseCardSectionTitle.vue")['default']>
  LazyBaseDialog: LazyComponent<typeof import("../../app/components/global/BaseDialog.vue")['default']>
  LazyBaseDivider: LazyComponent<typeof import("../../app/components/global/BaseDivider.vue")['default']>
  LazyBaseExpansionPanels: LazyComponent<typeof import("../../app/components/global/BaseExpansionPanels.vue")['default']>
  LazyBaseOverflowButton: LazyComponent<typeof import("../../app/components/global/BaseOverflowButton.vue")['default']>
  LazyBasePageTitle: LazyComponent<typeof import("../../app/components/global/BasePageTitle.vue")['default']>
  LazyButtonLink: LazyComponent<typeof import("../../app/components/global/ButtonLink.vue")['default']>
  LazyContextMenu: LazyComponent<typeof import("../../app/components/global/ContextMenu.vue")['default']>
  LazyCrudTable: LazyComponent<typeof import("../../app/components/global/CrudTable.vue")['default']>
  LazyDevDumpJson: LazyComponent<typeof import("../../app/components/global/DevDumpJson.vue")['default']>
  LazyDocLink: LazyComponent<typeof import("../../app/components/global/DocLink.vue")['default']>
  LazyDropZone: LazyComponent<typeof import("../../app/components/global/DropZone.vue")['default']>
  LazyHelpIcon: LazyComponent<typeof import("../../app/components/global/HelpIcon.vue")['default']>
  LazyImageCropper: LazyComponent<typeof import("../../app/components/global/ImageCropper.vue")['default']>
  LazyInputColor: LazyComponent<typeof import("../../app/components/global/InputColor.vue")['default']>
  LazyInputLabelType: LazyComponent<typeof import("../../app/components/global/InputLabelType.vue")['default']>
  LazyLanguageDialog: LazyComponent<typeof import("../../app/components/global/LanguageDialog.vue")['default']>
  LazyMarkdownEditor: LazyComponent<typeof import("../../app/components/global/MarkdownEditor.vue")['default']>
  LazyRecipeJsonEditor: LazyComponent<typeof import("../../app/components/global/RecipeJsonEditor.vue")['default']>
  LazyReportTable: LazyComponent<typeof import("../../app/components/global/ReportTable.vue")['default']>
  LazySafeMarkdown: LazyComponent<typeof import("../../app/components/global/SafeMarkdown.vue")['default']>
  LazyStatsCards: LazyComponent<typeof import("../../app/components/global/StatsCards.vue")['default']>
  LazyToggleState: LazyComponent<typeof import("../../app/components/global/ToggleState.vue")['default']>
  LazyWakelockSwitch: LazyComponent<typeof import("../../app/components/global/WakelockSwitch.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyVitePwaManifest: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
  LazyNuxtPwaManifest: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
  LazyNuxtPwaAssets: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']>
  LazyPwaAppleImage: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']>
  LazyPwaAppleSplashScreenImage: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']>
  LazyPwaFaviconImage: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']>
  LazyPwaMaskableImage: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']>
  LazyPwaTransparentImage: LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']>
  LazyNuxtLinkLocale: LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
  LazySwitchLocalePathLink: LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
