name: PR CI

on:
  pull_request:
    branches:
      - mealie-next
  merge_group:
    types: [checks_requested]
    branches:
      - mealie-next

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.merge_group.head_ref }}
  cancel-in-progress: true

jobs:
  pull-request-lint:
    name: "Lint PR"
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/pull-request-lint.yml

  frontend-tests:
    name: "Frontend Tests"
    uses: ./.github/workflows/test-frontend.yml

  code-ql:
    name: "CodeQL"
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write
